#!/bin/sh
set -e

MODULE_NAME=qos-dkms
MODULE_VERSION=1.0.0
if [ "$1" = "configure" ]; then
    dkms add -m ${MODULE_NAME} -v ${MODULE_VERSION} || true
    for kver in $(ls /lib/modules/ 2>/dev/null); do
        [ -e /lib/modules/${kver}/build/Makefile ] || continue
        dkms build -m ${MODULE_NAME} -v ${MODULE_VERSION} -k ${kver} || true
        dkms install -m ${MODULE_NAME} -v ${MODULE_VERSION} -k ${kver} || true
    done
fi

exit 0
